module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./node_modules/flowbite/**/*.js"],
  theme: {
    extend: {
      fontFamily: {
        inter: ["Inter"],
      },

      colors: {
        addButton: "#B10494",
        text: "#853177",
        bgRow: "#F9F9F9",
        border: "#E0E7ED",
        calenderbg: "#F5F1F5",
        outline: "#BEC8D0",
        application: "#2A07E3",
        applicationbg: "#ECEAF4",
        tech: "#AF1DC8",
        techbg: "#FADEFF",
        hr: "#ED8102",
        hrbg: "#FFFDE8",
        mgmt: "#189D7D",
        mgmtbg: "#E8FFE0",
        home: "#E21A1A",
        homebg: "#FFE8E8",
        offer: "#FFFFFF",
        offerbg: "#2A07E3",

        label: "#EBFDFF",
        LABEL_BG: "#1ABBB9",
        COMPLETED_COLOR: "#18AB56",
        COMPLETED_BG: "#EFFFF6",
        REJECTED_COLOR: "#C93131",
        REJECTED_BG: "#FFECEC",
        WAITING_COLOR: "#E86F00",
        WAITING_BG: "#FFF5EB",
        INACTIVE_COLOR: "#828282",
        INACTIVE_BG: "#EDEBEB",
        PROCESS_COLOR: "#E86F00",
        PROCESS_BG: "#FFF5EB",
      },
    },
  },
  plugins: [require("flowbite/plugin")],
};
